id: samsungce.robotCleanerMonitoringAutomation
version: 1
status: proposed
name: Robot Cleaner Monitoring Automation
ephemeral: false
attributes: {}
commands:
  enableMonitoringAutomation:
    name: enableMonitoringAutomation
    arguments: []
    sensitive: false
